import fs from 'fs';
// We don't have three/examples/jsm in node readily without transpiling, let's just use gltf-pipeline or basic inspection...
// Actually I can just write a quick HTML script or use the browser node...
